# -*- coding: utf-8 -*-
"""NPS_Admission_form_no_automation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UwEO_9FwcMSz-x77DW76V_S689SCNZNQ
"""

# ==========================================================
# NALANDA PUBLIC SCHOOL
# Admission Form Numbering Script
# ==========================================================

# Install required libraries (run once in Colab)
!pip install reportlab PyPDF2

from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4
from PyPDF2 import PdfReader, PdfWriter
import io
import copy

# ==========================================================
# USER SETTINGS
# ==========================================================

# Admission number range
start_number = 2201   # ONLY ENTER THIS
end_number = 2300     # ONLY ENTER THIS

# First page template (where number should be printed)
first_page_pdf = "Application_form.pdf"

# Second page template
second_page_pdf = "Application_form_page2.pdf"

# Position of admission number
# Adjust if needed
x_position = 65
y_position = 697

# Font settings
font_name = "Courier-Bold"
font_size = 18

# ==========================================================
# AUTO GENERATED OUTPUT FILE NAME
# ==========================================================

output_pdf = (
    f"New Admission Application Form "
    f"{start_number} to {end_number}.pdf"
)

# ==========================================================
# LOAD PDF TEMPLATES
# ==========================================================

reader_first = PdfReader(first_page_pdf)
reader_second = PdfReader(second_page_pdf)

first_page_template = reader_first.pages[0]
second_page_template = reader_second.pages[0]

# Final PDF writer
writer = PdfWriter()

# ==========================================================
# GENERATE FORMS
# ==========================================================

for number in range(start_number, end_number + 1):

    # ------------------------------------------------------
    # Create number overlay
    # ------------------------------------------------------

    packet = io.BytesIO()

    can = canvas.Canvas(packet, pagesize=A4)

    can.setFont(font_name, font_size)

    can.drawString(
        x_position,
        y_position,
        str(number)
    )

    can.save()

    packet.seek(0)

    overlay_pdf = PdfReader(packet)

    # ------------------------------------------------------
    # Create fresh copy of first page
    # ------------------------------------------------------

    numbered_first_page = copy.copy(first_page_template)

    numbered_first_page.merge_page(
        overlay_pdf.pages[0]
    )

    # ------------------------------------------------------
    # Add Page 1 (with admission number)
    # ------------------------------------------------------

    writer.add_page(numbered_first_page)

    # ------------------------------------------------------
    # Add Page 2
    # ------------------------------------------------------

    writer.add_page(
        copy.copy(second_page_template)
    )

# ==========================================================
# SAVE FINAL PDF
# ==========================================================

with open(output_pdf, "wb") as file:
    writer.write(file)

print("===================================")
print("PDF CREATED SUCCESSFULLY")
print(output_pdf)
print("===================================")